import { Dimensions, StyleSheet } from "react-native";
import {
  Align,
  BodyFontRegular,
  BorderRadius,
  Color,
  FontFamily,
  Gap,
  HeadingFont,
  MobileHeight,
  Padding,
} from "./GlobalStyles";

export const ComponentStyles = StyleSheet.create({
  loginContainer: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    gap: 90,
  },
  loginIllustration: {
    flex: 1,
    maxWidth: "50%",
    resizeMode: "contain",
  },
  loginFormContainer: {
    borderRadius: 10,
    backgroundColor: "white",
    paddingVertical: 24,
    paddingHorizontal: 20,
    gap: 30,
  },
  loginFormLabel: {
    ...HeadingFont.heading5,
    fontWeight: 700,
    fontFamily: FontFamily.default,
    color: Color.gray500,
    textAlign: "center",
  },
  formInputContainer: {
    maxWidth: 288,
    width: 288,
    gap: 10,
  },
  formChildrenWithIconContainer: {
    height: 48,
    justifyContent: "center",
    alignContent: "center",
  },
  formInputWithRightIconStyle: {
    ...BodyFontRegular.medium,
    height: 48,
    borderRadius: 4,
    padding: 12,
    paddingRight: 32,
    backgroundColor: Color.gray100,
  },
  inputContainer: {
    ...BodyFontRegular.medium,
    height: 48,
    backgroundColor: Color.gray100,
    padding: 8,
    borderRadius: 4,
  },
  formRightIconStyle: {
    flex: 1,
    position: "absolute",
    right: 0,
  },
  globalLoadingImageStyle: {
    height: 64,
    width: 64,
  },
  qrResultContainer: {
    alignItems: "center",
    padding: 10,
    backgroundColor: "#F0F0F0",
    borderRadius: 8,
  },
  qrResultText: {
    fontSize: 16,
    marginBottom: 10,
    textAlign: "center",
  },
  centeredButtonContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    gap: 32,
  },
  centeredButtonContainer1: {
    alignItems: "center",
    justifyContent: "center",
    gap: 32,
  },
  image: {
    width: 253,
    height: 253,
  },
  camera: {
    flex: 1,
  },
  buttonContainer1: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "transparent",
    margin: 64,
  },
  button: {
    flex: 1,
    alignSelf: "flex-end",
    alignItems: "center",
  },
  text: {
    fontSize: 24,
    fontWeight: "bold",
    color: "white",
  },
  globalLoadingContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    justifyContent: "center",
    zIndex: 1000,
    alignItems: "center",
  },
  uploadButtonText: {
    fontFamily: FontFamily.default,
    ...BodyFontRegular.small,
    fontWeight: 700,
    lineHeight: 16,
    // color: Color.gray400,
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
    elevation: 1,
    shadowColor: "#03153D",
    shadowOpacity: 0.1,
  },
  submitButtonText: {
    fontFamily: FontFamily.default,
    ...BodyFontRegular.medium,
    fontWeight: 600,
    color: Color.white,
    lineHeight: 24,
    justifyContent: "center",
  },
  payment: {
    ...BodyFontRegular.large,
    lineHeight: 24,
    fontWeight: 700,
    fontFamily: FontFamily.default,
    color: Color.gray500,
  },
  paymentItem: {
    fontFamily: FontFamily.item,
    fontWeight: 400,
    ...BodyFontRegular.large,
    lineHeight: 24,
    color: Color.gray500,
  },
  paymentQtyItem: {
    fontFamily: FontFamily.item,
    fontWeight: 400,
    ...BodyFontRegular.medium,
    lineHeight: 19,
    color: Color.gray400,
  },
  itemTotalCount: {
    fontFamily: FontFamily.default,
    fontWeight: 600,
    ...BodyFontRegular.medium,
    lineHeight: 24,
    color: Color.gray500,
  },
  itemTotalPrice: {
    fontFamily: FontFamily.default,
    fontWeight: 700,
    ...BodyFontRegular.medium,
    lineHeight: 24,
    color: Color.gray400,
  },
  textItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: 600,
  },
  totalContainer: {
    width: 873,
    height: 142,
    paddingVertical: 23,
    gap: 24,
    borderWidth: 1,
    borderBottomWidth: 1,
    borderBottomColor: "#D0D4D9",
  },
  itemTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: 800,
  },
  itemPrice: {
    fontFamily: FontFamily.default,
    fontWeight: 700,
    ...BodyFontRegular.large,
    lineHeight: 24,
    color: Color.gray400,
    gap: 10,
  },
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
  },
  itemContainer: {
    flexDirection: "row",
    width: 811,
    height: 94,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 24,
    gap: 12,
    color: Color.gray100,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  modalHeader2: {
    flexDirection: "row",
    gap: 20,
    height: 67,
    width: 504,
  },
  modalHeader3: {
    flex: 1,
    height: 67,
    gap: 10,
  },
  modalText: {
    height: 40,
    backgroundColor: Color.gray100,
    padding: 8,
  },
  header4: {
    flexDirection: "row",
    alignContent: "center",
    paddingTop: 12,
    justifyContent: "space-between",
    alignItems: "center",
  },
  addBAProductButton: {
    backgroundColor: Color.primary,
    flexDirection: "row",
    gap: 16,
    borderRadius: BorderRadius.b4,
    paddingHorizontal: 24,
    paddingVertical: 8,
  },

  saveButtonLabel: {
    color: Color.white,
    fontSize: 16,
    lineHeight: 24,
  },
  saveButton: {
    backgroundColor: Color.primary,
    borderRadius: 4,
    flexDirection: "row",
    gap: 10,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: 455,
    height: 615,
    gap: 16,
    borderRadius: 8,
    alignItems: "flex-start",
    backgroundColor: Color.white,
    paddingHorizontal: 20,
    paddingVertical: 16,
    elevation: 10,
  },
  modalHeaderLabel1: {
    ...HeadingFont.heading6,
    color: Color.gray500,
    justifyContent: "center",
    marginLeft: "auto",
  },
  modalTextInputContainer: {
    height: 40,
    backgroundColor: Color.gray100,
    padding: 8,
  },

  drawerLogoContainer: {
    alignItems: "center",
    marginTop: 48,
  },

  drawerAllItemsContainer: {
    gap: 10,
    marginTop: 48,
    marginHorizontal: 28,
  },
  drawerContentScrollCointainer: {
    flex: 2,
    paddingTop: 0,
    paddingBottom: 20,
    height: MobileHeight,
  },
  drawerHeaderCointainer: {
    height: 84,
    alignItems: Align.center,
    backgroundColor: Color.white,
    flexDirection: "row",
    paddingHorizontal: 16,
    marginBottom: 16,
    gap: 10,
  },
  drawerHeaderCointainer1: {
    alignItems: Align.center,
    backgroundColor: Color.white,
    flexDirection: "row",

    marginBottom: 16,
    gap: 10,
  },
  drawerHeaderTitleContainer: {
    alignItems: Align.center,
  },
  drawerItemContainer: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  drawerItemInsideContainer: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    width: "100%",
  },
  drawerItemContainerSelected: {
    gap: 8,
    backgroundColor: Color.primary,
    borderRadius: 4,
  },
  drawerItem2Container: {
    flexDirection: "row",
    gap: 10,
  },
  drawerItemLabelContainer: {
    fontFamily: FontFamily.default,
    fontSize: 14,
    lineHeight: 16,
    fontWeight: "400",
    color: Color.primary,
  },
  drawerItemLabelContainer1: {
    fontFamily: FontFamily.default,
    fontSize: 14,
    lineHeight: 16,
    fontWeight: "400",
    color: Color.white,
  },
  drawerItemLabelContainerSelected: {
    fontFamily: FontFamily.default,
    fontSize: 14,
    lineHeight: 16,
    fontWeight: "700",
    color: Color.white,
  },
  defaultButtonStyle: {
    padding: 10,
    borderRadius: 10,
  },
  iconButtonStyle: {
    height: 44,
    width: 44,
  },
  disableButtonTitleStyle: {
    ...BodyFontRegular.medium,
    textAlign: "center",
  },

  primaryButtonStyle: {
    borderRadius: 4,
    backgroundColor: Color.primary,
    height: 44,
  },
  primaryButtonTitleStyle: {
    ...BodyFontRegular.medium,
    textAlign: "center",
    color: Color.white,
  },

  primaryButtonWithLeftIconStyle: {
    height: 44,
    flexDirection: "row",
    gap: 10,
    justifyContent: Align.center,
  },
  settingsBadminButtonWithLeftIconStyle: {
    height: 44,
    flexDirection: "row",
    gap: 10,
  },

  secondaryButtonStyle: {
    backgroundColor: Color.secondary,
    borderColor: Color.primary,
    borderWidth: 1,
    borderRadius: BorderRadius.b10,
    height: 44,
  },
  secondaryButtonTitleStyle: {
    ...BodyFontRegular.medium,
    color: Color.primary,
  },
  secondaryButtonWithLeftIconStyle: {
    backgroundColor: Color.secondary,
    borderColor: Color.primary,
    borderWidth: 1,
    borderRadius: BorderRadius.b10,
    height: 44,
    flexDirection: "row",
    gap: 10,
    justifyContent: Align.center,
  },

  headerCointainer: {
    height: 84,
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: Align.center,
    backgroundColor: Color.white,
    flexDirection: "row",
  },
  headerLabelStyle: {
    ...HeadingFont.heading6,
    color: Color.gray500,
  },
  headerTitleContainer: {
    flex: 1,
    position: "absolute",
    alignItems: Align.center,
    left: 0,
    right: 0,
  },
  themedInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: 240,
    height: 40,
    backgroundColor: Color.gray100,
    borderRadius: BorderRadius.b4,
    gap: 10,
    padding: 8,
  },
  themedInput: {
    flex: 1,
    fontFamily: FontFamily.default,
    fontWeight: "400",
    ...BodyFontRegular.medium,
    color: Color.placeholder_qty,
    lineHeight: 24,
    gap: 8,
    justifyContent: "center",
    padding: 8,
  },
  formDropDownStyle: {
    borderWidth: 1,
    borderRadius: 4,
    width: "100%",
    alignItems: Align.center,
    padding: 12,
    backgroundColor: Color.white,

    // borderColor: Color.gray300,
    height: 48,
    margin: 0,
    flex: 1,
  },
  formDropDownStyle1: {
    borderRadius: 4,
    width: "100%",
    alignItems: Align.center,
    padding: 8,
    backgroundColor: Color.gray100,
    gap: 10,

    // borderColor: Color.gray300,
    height: 48,
    margin: 0,
    flex: 1,
  },
  formDropDownSelectedStyle: {
    fontWeight: "500",
    color: Color.gray600,
  },
  formDropDownSelectedStyle1: {
    ...BodyFontRegular.medium,
    fontWeight: "500",
    color: Color.gray600,
  },
  formDropdownList: {
    height: 48,
    borderBottomWidth: 1,
    // borderColor: Color.gray300,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    zIndex: 100,
    flex: 1,
    width: "100%",
    paddingHorizontal: 20,
  },
  headerCointainerTable: {
    // height: 84,
    // paddingVertical: 16,
    // paddingHorizontal: 20,
    alignItems: Align.center,
    flexDirection: "row",
    flex: 1,
  },
  headerLabelTableStyle: {
    ...HeadingFont.heading6,
    color: Color.white,
  },
  headerTitleTableContainer: {
    position: "absolute",
    // alignItems: Align.center,
    left: 0,
    right: 0,
  },
  cashStatusContainer: {
    backgroundColor: Color.blue1,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    flexDirection: "column",
    gap: 4,
  },
  cashStatusLabel1: {
    fontSize: 14,
    color: Color.gray400,
    lineHeight: 16,
  },
  cashStatusLabel2: {
    fontSize: 20,
    color: Color.gray500,
    lineHeight: 24,
  },
  tabContainer1: {
    borderRadius: 24,
    borderWidth: 1,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderColor: Color.primary,
    height: 40,
    overflow: "hidden",
  },
  reportSalesTabContainer: {
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    borderWidth: 1,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderColor: Color.primary,
    height: 40,
    overflow: "hidden",
  },
  reportVoidsTabContainer: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
    paddingVertical: 8,
    paddingHorizontal: 16,
    height: 40,
    backgroundColor: Color.primary,
    borderColor: Color.primary,
  },
  tabContainer2: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
    paddingVertical: 8,
    paddingHorizontal: 16,
    height: 40,
    backgroundColor: Color.primary,
    borderColor: Color.primary,
  },
  tabContainer3: {
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    borderWidth: 1,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderColor: Color.primary,
    height: 40,
    overflow: "hidden",
  },
  tabLabel2: {
    color: Color.white,
  },
  tabLabelCollection: {
    overflow: "hidden",
  },
  tabLabelCollection1: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  reportsTabLabelCollection: {
    flexDirection: "row",
    alignItems: "center",
  },
  calendarContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Color.gray100,
    borderRadius: 4,
    padding: 8,
    gap: 10,
    width: 150,
    height: 40,
    justifyContent: "space-between",
  },
  textInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Color.gray100,
    borderRadius: 4,
    padding: 8,
    gap: 10,
    width: 150,
    height: 40,
  },
  textInputContainer2: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Color.gray100,
    borderRadius: 4,
    padding: 8,
    gap: 10,
    width: 200,
    height: 40,
    justifyContent: "space-between",
  },
  textInputContainerProduct: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Color.gray100,
    borderRadius: 4,
    padding: 8,
    gap: 10,
    height: 40,
    width: 240,
  },
  textSearchInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Color.gray100,
    borderRadius: 4,
    padding: 8,
    gap: 10,
    width: 240,
    height: 40,
  },
  textInputContainer1: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Color.gray100,
    borderRadius: 4,
    width: 240,
  },
  textInputLabel: {
    fontSize: 16,
    color: Color.gray1,
  },
  subTextInputContainer: {
    flexDirection: "row",
    gap: 16,
  },
  subTextInputContainer1: {
    flexDirection: "row",
    gap: 16,
  },
  sendButtonContainer: {
    borderWidth: 1.5,
    borderColor: Color.primary,
    borderRadius: 4,
    height: 40,
    width: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  generateButtonLabel: {
    color: Color.white,
    fontSize: 16,
    lineHeight: 24,
  },
  scanButtonLabel: {
    color: Color.primary,
    fontSize: 16,
    lineHeight: 24,
  },
  generateButton: {
    backgroundColor: Color.primary,
    borderRadius: 4,
    flexDirection: "row",
    gap: 10,
    width: 134,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  scanButton: {
    backgroundColor: Color.white,
    borderRadius: 4,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  tableHead: {
    height: 48,
    backgroundColor: Color.secondary,
    color: Color.gray400,
    borderRadius: 8,
  },
  tableHeadingText: {
    color: Color.gray400,
    paddingVertical: 16,
    paddingHorizontal: 20,
    fontSize: 14,
    lineHeight: 16,
    fontWeight: 700,
  },
  tableText: {
    color: Color.gray400,
    paddingVertical: 16,
    paddingHorizontal: 20,
    fontSize: 14,
    lineHeight: 16,
  },
  tableStyleContainer: {
    paddingHorizontal: 20,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    display: "flex",
    flexGrow: 1,
    flex: 1,
  },
  overlayContainerGenerate: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  closeButtonStyle: {
    borderRadius: 24,
    backgroundColor: Color.white,
  },
  generateHeaderModal: {
    padding: 16,
    gap: 16,
    borderRadius: 8,
    flexDirection: "column",
    backgroundColor: Color.white,
    width: 455,
  },
  generateSubHeaderModal: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  generateHeaderLabel: {
    fontWeight: 700,
    fontSize: 20,
    lineHeight: 24,
  },
  generateModalContainer: {
    flexDirection: "column",
  },
  generateLabelText: {
    fontSize: 14,
    lineHeight: 16,
  },
  generateEmailContainer: {
    gap: 8,
    flexDirection: "column",
  },
  generateCancelButton: {
    borderRadius: 4,
    borderWidth: 1.5,
    paddingVertical: 8,
    paddingHorizontal: 24,
    borderColor: Color.primary,
    backgroundColor: Color.white,
    width: 130,
    alignItems: "center",
  },
  generateSendButton: {
    borderRadius: 4,
    borderWidth: 1.5,
    paddingVertical: 8,
    paddingHorizontal: 24,
    borderColor: Color.primary,
    backgroundColor: Color.primary,
    width: 130,
    alignItems: "center",
  },
  generateButtonContainer: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 16,
  },
  generateInputButtonStyle: {
    flexDirection: "column",
    gap: 24,
  },
  generateSendLabel: {
    color: Color.white,
  },
  generateCancelLabel: {
    color: Color.primary,
  },
  tableHeaderGroup: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
  },
  tableHeaderLabel: {
    color: Color.white,
    justifyContent: "center",
  },
  tableHeaderLabel1: {
    color: Color.gray600,
    justifyContent: "center",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: 700,
  },
  tableHeaderLabel3: {
    fontFamily: FontFamily.default,
    ...HeadingFont.heading2,
    color: Color.primary,
    justifyContent: "center",
    lineHeight: 56,
    fontWeight: 700,
  },
  amountReceived: {
    fontFamily: FontFamily.default,
    ...BodyFontRegular.small,
    lineHeight: 16,
    fontWeight: 400,
    color: Color.gray500,
  },
  enterAmountReceivedContainer: {
    width: 267,
    height: 40,
    backgroundColor: Color.gray100,
    padding: 8,
    borderRadius: 4,
  },
  enterAmountReceivedText: {
    ...BodyFontRegular.medium,
    fontFamily: FontFamily.default,
    lineHeight: 24,
    backgroundColor: Color.gray1,
  },
  tableHeaderLabel2: {
    color: Color.white,
  },
  productHeader: {
    fontSize: 20,
    lineHeight: 24,
    fontWeight: 600,
    textAlign: "center",
  },
  tabLabelCollectionSAProduct: {
    justifyContent: "space-between",
    gap: 8,
  },
  addNewProductButton: {
    backgroundColor: Color.primary,
    borderRadius: 4,
    flexDirection: "row",
    gap: 10,
    width: 213,
    alignItems: "center",
    justifyContent: "center",
    height: 40,
  },
  replenishButton: {
    backgroundColor: Color.primary,
    borderRadius: 4,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    justifyContent: "center",
    height: 40,

    paddingVertical: 8,
    paddingHorizontal: 24,
  },

  addNewProductButton1: {
    backgroundColor: Color.white,
    borderWidth: 1,
    borderColor: Color.primary,
    borderRadius: 4,
    flexDirection: "row",
    gap: 10,
    width: 213,
    alignItems: "center",
    justifyContent: "center",
  },
  addNewProductButtonReplenish: {
    backgroundColor: Color.white,
    borderWidth: 1,
    borderColor: Color.primary,
    borderRadius: 4,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    justifyContent: "center",
    height: 40,

    paddingVertical: 8,
    paddingHorizontal: 24,
  },
  addNewProductLabel: {
    color: Color.white,
    fontSize: 16,
    lineHeight: 24,
  },

  addProductLabel: {
    color: Color.primary,
    fontSize: 16,
    lineHeight: 24,
  },
  addNewProductLabel1: {
    color: Color.primary,
    fontSize: 16,
    lineHeight: 24,
  },
  settingsButtonWithLeftIconStyle: {
    height: 44,
    flexDirection: "row",
    gap: 10,
  },

  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  replenishModalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",

    paddingHorizontal: 24,
    paddingVertical: 20,
  },

  promptModalBackground: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  promptModalContainer: {
    flexDirection: "column",
    gap: 28,
    backgroundColor: Color.white,
    paddingHorizontal: 20,
    paddingVertical: 16,
    elevation: 10,
    borderRadius: 12,
  },
  promptLabel: {
    fontFamily: FontFamily.default,
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "400",
  },
  promptRightAligner: {
    alignItems: "flex-end",
  },
  promptButtonContainer: {
    flexDirection: "row",
    gap: 12,
  },
  promptYesButtonLabel: {
    fontFamily: FontFamily.default,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "600",
    color: Color.white,
  },
  promptYesButton: {
    backgroundColor: Color.primary,
    width: 75,
    borderRadius: 4,
    alignItems: "center",
  },
  promptNoButtonLabel: {
    fontFamily: FontFamily.default,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "600",
    color: Color.primary,
  },
  promptNoButton: {
    backgroundColor: Color.white,
    width: 75,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: Color.primary,
    alignItems: "center",
  },
  promptCloseButton: {
    width: 24,
    height: 24,
    backgroundColor: "white",
    elevation: 10,
    borderRadius: 99,
    alignItems: "center",
    justifyContent: "center",
  },

  StoreAddUserModalContent: {
    height: 450,
    width: 552,
    backgroundColor: Color.white,
    paddingHorizontal: 20,
    paddingVertical: 16,
    elevation: 10,
    gap: 10,
    borderRadius: 12,
  },

  replenishModalContent: {
    width: 552,
    backgroundColor: Color.white,
    paddingHorizontal: 20,
    paddingVertical: 16,
    elevation: 10,
    gap: 10,
    borderRadius: 12,
  },

  StoreSendInputEmailModalContent: {
    height: 261,
    width: 300,
    backgroundColor: Color.white,
    paddingHorizontal: 20,
    paddingVertical: 16,
    elevation: 10,
    gap: 10,
    borderRadius: 12,
  },

  StoreProductReportModalContent: {
    height: 227,
    width: 552,
    backgroundColor: Color.white,
    paddingHorizontal: 20,
    paddingVertical: 16,
    elevation: 10,
    gap: 10,
    borderRadius: 12,
  },
  uploadGcashModalContent: {
    height: 450,
    width: 552,
    backgroundColor: Color.white,
    paddingHorizontal: 20,
    paddingVertical: 24,
    gap: 40,
    borderRadius: 12,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingBottom: 28,
  },
  modalCloseIcon: {
    marginLeft: "auto",
    justifyContent: "flex-end",
  },
  modalHeader1: {
    flexDirection: "column",
    gap: Gap.gap24,
  },

  StoreAddProductModalContent: {
    height: 441,
    width: 552,
    backgroundColor: Color.white,
    paddingHorizontal: 20,
    paddingVertical: 16,
    elevation: 10,
    gap: 10,
    borderRadius: 12,
  },

  CashierOrderSuccessModalContent: {
    height: 377,
    width: 555,
    backgroundColor: Color.white,
    paddingHorizontal: 20,
    paddingVertical: 16,
    elevation: 10,
    gap: 10,
    borderRadius: 12,
  },

  CashierVoidTransactionConfirmModalContent: {
    height: 160,
    width: 455,
    backgroundColor: Color.white,
    paddingHorizontal: 20,
    paddingVertical: 16,
    elevation: 10,
    gap: 16,
    borderRadius: 12,
  },
  CashierVoidTransactionConfirmPasswordModalContent: {
    height: 251,
    width: 455,
    backgroundColor: Color.white,
    paddingHorizontal: 20,
    paddingVertical: 16,
    elevation: 10,
    gap: 16,
    borderRadius: 12,
  },

  selfCenter: {
    alignSelf: "center",
  },

  modalButtonContainer: {
    alignSelf: "flex-end",
    paddingTop: Padding.p24,
    gap: 16,
  },
  modalButtonContainer1: {
    alignSelf: "flex-end",
  },
  modalButton: {
    color: Color.white,
    ...BodyFontRegular.medium,
  },

  modalUploadButtonContainer: {
    alignSelf: "flex-start",
    gap: 24,
    paddingVertical: 20,
  },

  camera1: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },

  modalButtonFill: {
    borderColor: Color.primary,
    borderWidth: 1.5,
    backgroundColor: Color.primary,
    flexDirection: "row",
    gap: 16,
    borderRadius: BorderRadius.b4,
    paddingHorizontal: 24,
    paddingVertical: 8,
  },
  submitButtonFill: {
    backgroundColor: Color.primary,
    flexDirection: "row",
    gap: 16,
    paddingHorizontal: 24,
    paddingVertical: 8,
    borderRadius: 4,
  },

  buttonSubmit: {
    borderColor: Color.primary,
    borderWidth: 1.5,
    backgroundColor: Color.primary,
    flexDirection: "row",
    gap: 16,
    borderRadius: BorderRadius.b4,
    paddingHorizontal: 24,
    paddingVertical: 8,
  },

  modalButtonOutline: {
    borderColor: Color.primary,
    borderWidth: 1.5,
    flexDirection: "row",
    gap: 16,
    borderRadius: BorderRadius.b4,
    paddingHorizontal: 24,
    paddingVertical: 8,
  },

  modalUploadButtonOutline: {
    borderColor: Color.primary,
    borderWidth: 1.5,
    flexDirection: "row",
    gap: 10,
    borderRadius: BorderRadius.b4,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },

  addProductButton: {
    backgroundColor: Color.primary,
    flexDirection: "row",
    gap: 16,
    borderRadius: BorderRadius.b4,
    paddingHorizontal: 24,
    paddingVertical: 8,
  },

  modalHeaderContainer: {
    flexDirection: "row",
    paddingBottom: 28,
    justifyContent: "space-between",
  },

  modalHeaderLabel: {
    fontFamily: FontFamily.default,
    fontWeight: "700",
    fontSize: 20,
    lineHeight: 24,
    color: Color.gray500,
  },
  modalFieldLabel: {
    fontFamily: FontFamily.default,
    fontWeight: "500",
    fontSize: 14,
    lineHeight: 19,
    color: Color.gray3,
  },

  replenishModalContentContainerOuter: {
    flexDirection: "column",
    gap: 24,
  },
  replenishModalContentContainerInner: {
    flexDirection: "row",
    gap: 20,
    height: 67,
  },
  replenishModalContentContainerInner2: {
    flexDirection: "column",
    gap: 8,
  },
  replenishModalContentContainerInner3: {
    flex: 1,
    height: 67,
    gap: 10,
  },
  replenishModalButtonContainer: {
    flexDirection: "row",
    alignContent: "center",
    paddingTop: 12,
    justifyContent: "flex-end",
  },
  replenishModalButtonIcon: {
    width: 18,
    height: 18,
    alignSelf: "center",
  },

  modalHeaderLabelPosStart: {
    ...HeadingFont.heading6,
    color: Color.gray500,
    justifyContent: "center",
  },
  receiptPrimaryButtonStyle: {
    borderRadius: 4,
    backgroundColor: Color.red,
    height: 44,
  },
  receiptPrimaryButtonTitleStyle: {
    ...BodyFontRegular.medium,
    textAlign: "center",
    color: Color.white,
  },
  receiptSecondaryButtonStyle: {
    backgroundColor: Color.secondary,
    borderColor: Color.red,
    borderWidth: 1,
    borderRadius: BorderRadius.b4,
    height: 44,
  },
  receiptMainContainer: {
    flex: 1,
    paddingVertical: 20,
    gap: 24,
    justifyContent: "flex-start",
    alignItems: "center",
    minWidth: 350,
  },
  receiptPdfContainer: {
    flex: 1,
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
  },
  receiptButtonContainer: {
    gap: 24,
    minWidth: 350,
  },
  receiptSecondaryButtonTitleStyle: {
    ...BodyFontRegular.medium,
    textAlign: "center",
    color: Color.red,
  },
  receipt: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginBottom: 12,
  },
  receiptDetails: {
    fontSize: 12,
    fontWeight: "400",
    color: Color.gray500,
  },
  receiptTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  receiptTotalText: {
    fontSize: 16,
    fontWeight: "400",
    fontFamily: FontFamily.default,
  },
  receiptPayChange: {
    gap: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "stretch",
    alignContent: "stretch",
    alignSelf: "stretch",
    minWidth: 350,
  },
  receiptTextLight: {
    fontSize: 14,
    fontWeight: "400",
    fontFamily: FontFamily.default,
    color: Color.gray400,
  },
  center: {
    alignItems: "center",
    justifyContent: "center",
  },
  receiptButtonText: {
    fontWeight: "600",
    fontSize: 16,
    fontFamily: FontFamily.default,
    color: Color.red,
  },
  receiptButton: {
    height: 40,
    borderRadius: 4,
    borderWidth: 1.5,
    paddingVertical: 8,
    paddingHorizontal: 24,
    borderColor: Color.red,
  },
  voidTransHead: {
    fontWeight: "700",
    fontSize: 20,
    color: Color.gray500,
  },
  voidTransText: {
    fontWeight: "400",
    fontSize: 14,
    color: Color.gray400,
  },
  voidTransPass: {
    fontWeight: "400",
    fontSize: 14,
    color: Color.gray500,
  },
  voidTransSButtonText: {
    fontWeight: "400",
    fontSize: 16,
    color: Color.blue2,
  },
  voidTransSButton: {
    height: 40,
    borderRadius: 4,
    borderWidth: 1.5,
    paddingVertical: 8,
    paddingHorizontal: 24,
    borderColor: Color.blue2,
  },
  voidTransPButtonText: {
    fontWeight: "400",
    fontSize: 16,
    color: Color.white,
  },
  voidTransPButton: {
    height: 40,
    borderRadius: 4,
    paddingVertical: 8,
    paddingHorizontal: 24,
    backgroundColor: Color.blue2,
  },
  productModalScroll: {
    height: 214,
    gap: 16,
  },
  productProps: {
    fontSize: 14,
    fontWeight: "400",
    color: Color.body,
  },
  productType: {
    flexDirection: "row",
    gap: 16,
  },
  productTypeText: {
    fontWeight: "400",
    fontSize: 16,
    color: Color.body,
  },
  productQuantity: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  productPrice: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  toastContainer: {
    flexDirection: "row",
    gap: 10,
    alignContent: "center",
    alignItems: "center",
  },
  successToastContainer: {
    position: "absolute",
    backgroundColor: Color.success2,
    borderRadius: 6,
    paddingVertical: 8,
    paddingHorizontal: 16,
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    alignSelf: "center",
    bottom: 30,
  },
  successToastLabelStyle: {
    ...BodyFontRegular.small,
    color: Color.success,
  },

  errorToastContainer: {
    position: "absolute",
    backgroundColor: Color.error1,
    borderRadius: 6,
    paddingVertical: 8,
    paddingHorizontal: 16,
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    alignSelf: "center",
    bottom: 30,
  },
  errorToastLabelStyle: {
    ...BodyFontRegular.small,
    color: Color.error,
  },
  replenishSubHeader: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: 600,
  },
  replenishSubHeaderContainer: {
    gap: 10,
    flexDirection: "row",
  },
  selectionContainer: {
    flexDirection: "row",
    justifyContent: "flex-start",
    paddingVertical: 16,
    paddingHorizontal: 20,
    gap: 16,
  },
  selectionContainerReplenish: {
    flexDirection: "row",
    justifyContent: "flex-start",
    paddingVertical: 16,
    gap: 16,
  },
  cartContainer: {
    backgroundColor: Color.white,
    width: 319,
  },
  cartHeaderContainer1: {
    gap: 10,
    flexDirection: "row",
    justifyContent: "center",
  },
  cartNumberContainer: {
    backgroundColor: Color.primary,
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 100,
  },
  cartFirstContainer: {
    paddingVertical: 10,
    paddingHorizontal: 32,
    height: 68,
    justifyContent: "space-between",
    flexDirection: "row",
  },
  dineInButtonLabel: {
    fontSize: 14,
    lineHeight: 16,
    width: 97.5,
    textAlign: "center",
  },
  cashButtonLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: 600,
    textAlign: "center",
  },
  dineInButton: {
    borderColor: Color.primary,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 24,
    borderWidth: 1,
  },
  cashButton: {
    borderColor: Color.primary,
    paddingVertical: 8,
    paddingHorizontal: 24,
    borderRadius: 1.5,
    borderWidth: 1,
    gap: 10,
    width: 125,
    height: 40,
  },
  gcashButtonCollection: {
    width: 126,
    height: 40,
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 24,
    gap: 10,
    flexDirection: "row",
    backgroundColor: "white",
    borderColor: "#2196F3",
    borderWidth: 2,
  },
  cartButtonStyle: {
    gap: 10,
    paddingHorizontal: 32,
  },
  cartButtonCollection: {
    gap: 8,
    flexDirection: "row",
  },

  itemListContainer: {
    paddingVertical: 16,
    paddingHorizontal: 32,
  },
  orderItemContainer: {
    flexDirection: "row",
    gap: 16,
  },
  imageItemContainer: {
    width: 66,
    height: 66,
    backgroundColor: Color.bgGray,
    borderRadius: 8,
  },
  imageItem: {
    resizeMode: "contain",
  },
  itemTitle: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: 600,
  },
  itemDescriptionSection: {
    flexDirection: "row",
    gap: 16,
    justifyContent: "space-between",
    height: 32,
  },
  itemSubTitle: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: 400,
  },
  addItemSmallContainer: {
    backgroundColor: Color.primary,
    borderRadius: 4,
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  subTitleContainer: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 10,
  },
  flexContainer: {
    justifyContent: "center",
    flex: 1,
  },
  removeItemSmallContainer: {
    width: 24,
    height: 24,
    borderRadius: 4,
    borderWidth: 1,
    padding: 8,
    borderColor: Color.error,
    alignItems: "center",
    justifyContent: "center",
  },
  tabButtonStyle: {
    fontWeight: 700,
  },
  orderItemsContainer: {
    flexDirection: "row",
  },
  orderItemsItemView: {
    width: 131,
    gap: 10,
    marginRight: 40,
  },
  orderItemsItemName: {
    fontSize: 16,
    fontWeight: "bold",
  },
  orderItemsItemPrice: {
    fontSize: 14,
  },
  orderItemsItemImage: {
    width: "100%",
    height: 100, // Adjust image dimensions
    resizeMode: "cover", // Optional: resize mode for images
  },
  subTotalInfoContainer: {
    paddingVertical: 10,
    paddingHorizontal: 32,
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: Color.secondary,
  },
  serviceChargeInfoContainer: {
    paddingVertical: 10,
    paddingHorizontal: 32,
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: Color.secondary,
  },
  totalInfoContainer: {
    paddingVertical: 10,
    paddingHorizontal: 32,
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: Color.secondary,
  },
  proceedButtonLabel: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: 600,
    color: Color.white,
    alignItems: "center",
  },
  proceedButton: {
    paddingVertical: 8,
    paddingHorizontal: 24,
    borderRadius: 4,
    backgroundColor: Color.primary,
    alignItems: "center",
  },
  buttonMarginLeft: {
    marginLeft: "auto",
  },
  emailModalContainer: {
    gap: 24,
  },
  emailModalSubContainer: {
    height: 67,
    gap: 10,
  },
  emailModalLabel: {
    height: 19,
  },
  emailSendIcon: {
    width: 18,
    height: 18,
    alignSelf: "center",
  },

  qrCodeMainLayout: {
    flex: 1,
    justifyContent: Align.center,
    padding: 20,
    gap: 10,
  },
  qrCameraMainLayout: {
    flex: 1,
    justifyContent: Align.center,
  },

  // pagination start
  paginationNumberButton: {
    height: 32,
    width: 32,
    borderWidth: 1,
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  paginationLabelText: {
    alignSelf: "center",
    fontFamily: FontFamily.default,
    fontSize: 14,
    lineHeight: 16,
    fontWeight: "400",
  },
  paginationChevronButton: {
    height: 32,
    width: 32,
    borderWidth: 1,
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  paginationChevronFlip: {
    transform: [{ scaleX: -1 }],
  },
  paginationCountLabel: {
    color: Color.gray2,
    alignSelf: "center",
    fontFamily: FontFamily.default,
    fontSize: 14,
    lineHeight: 16,
    fontWeight: "400",
  },
  paginationContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 22,
    marginBottom: 20,
  },
  // pagination end
  CashierProductModalContainer: {
    height: 275,
    width: 625,
    backgroundColor: Color.white,
    justifyContent: "center",
    padding: 24,
    borderRadius: 8,
    flexDirection: "row",
    gap: 24,
  },
  productNameContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  deleteStyle: {
    borderWidth: 1,
    height: 24,
    width: 24,
    borderRadius: 4,
    borderColor: "red",
    alignItems: "center",
    justifyContent: "center",
  },
  addStyle: {
    height: 24,
    width: 24,
    borderRadius: 4,
    backgroundColor: Color.blue2,
    alignItems: "center",
    justifyContent: "center",
  },
  itemQuantity: {
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
  },
  payementsContainer: {
    padding: 24,
    gap: 20,
    backgroundColor: Color.white,
    flex: 1,
  },
  itemsContainer: {
    backgroundColor: Color.lightBlue,
    height: 94,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  itemDetails: { flexDirection: "row", gap: 16 },
  itemDetailArranged: { justifyContent: "center", flex: 1 },
  itemPricing: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexGrow: 1,
  },
  bottomDetails: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "white",
    padding: 16,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  bottomContainer: { gap: 25, marginBottom: 10 },
  line: { borderWidth: 0.5, height: 0.5 },
  totalCount: { flexDirection: "row", justifyContent: "space-between" },
  productActionsContainer: {
    flexDirection: "row",
    gap: 16,
    paddingLeft: 20,
  },
  sideContainer: {
    paddingVertical: 24,
    width: 319,
    backgroundColor: Color.white,
    elevation: 5,
  },
  sideHeadContainer: { paddingHorizontal: 24, gap: 24 },
  hPad: { paddingHorizontal: 32 },
  cAlign: { alignItems: "center" },
  gap8: { gap: 8 },
  input: {
    backgroundColor: Color.lightBlue,
    padding: 4,
    borderRadius: 4,
  },
  buttonContainer: {
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: 24,
    paddingVertical: 8,
    gap: 10,
    borderColor: Color.blue2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonContainer2: {
    height: 187,
    width: 203,
    borderWidth: 1,
    borderRadius: 12,
    padding: 20,
    gap: 20,
    borderColor: Color.white,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  enabledSubmitButtonGcashUpload: {
    width: 137,
    height: 40,
    padding: 8,
    paddingLeft: 24,
    paddingRight: 24,
    gap: 10,
    borderRadius: 4,
    opacity: 1,
    color: Color.primary,
  },
  disbledSubmitButtonGcashUpload: {
    width: 137,
    height: 40,
    padding: 8,
    paddingLeft: 24,
    paddingRight: 24,
    gap: 10,
    borderRadius: 4,
    opacity: 0.5,
    color: "#AEC0CE",
  },
  buttonContainerSelected: {
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: 24,
    paddingVertical: 8,
    gap: 10,
    backgroundColor: Color.darkBlue,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  paymentContainer: { flexDirection: "row", justifyContent: "center", gap: 16 },
  padV: { paddingVertical: 16 },
  prodCon: { flexDirection: "row", gap: 16 },
  f1: { flex: 1 },
  f1Jc: { flex: 1, justifyContent: "space-between" },
  centerView: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  productModal: { flexDirection: "row", gap: 24 },
  imageSize: { width: 225, height: 225 },
  wg: { width: 300, gap: 24 },
  g24: { gap: 24 },
  radioInputContainer: {
    flexDirection: "row",
    gap: 16,
  },
  singleRadioInput: {
    backgroundColor: Color.lightBlue,
    width: 203,
    padding: 8,
    borderRadius: 4,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  radio: {
    borderWidth: 1,
    borderColor: Color.grey,
    height: 24,
    width: 24,
    borderRadius: 24,
  },
  radioSelected: {
    borderWidth: 1,
    backgroundColor: Color.grey,
    borderColor: Color.grey,
    height: 24,
    width: 24,
    borderRadius: 24,
  },
  sideBarContainer: { flex: 1, padding: 32, justifyContent: "flex-end" },
  touchableOpacityContainer1: {
    position: "absolute",
    bottom: 10,
    paddingVertical: 8,
    paddingHorizontal: 6,
    backgroundColor: Color.secondary,
    borderRadius: 24,
  },
  drawerIconContainer: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    width: "100%",
  },
  addSupplierButton: {
    backgroundColor: Color.primary,
    borderRadius: 4,
    flexDirection: "row",
    gap: 10,
    width: 213,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-end",
    height: 40,
  },

  AddSupplierModalContent: {
    height: 615,
    width: 455,
    backgroundColor: Color.white,
    paddingHorizontal: 20,
    paddingVertical: 16,
    elevation: 10,
    gap: 10,
    borderRadius: 12,
  },
  menuImage: { width: 131, height: 131 },
  menuContainer: { flexGrow: 1, gap: 20 },
  cartImage: { width: 66, height: 66 },
  modalImage: { width: 225, height: 225 },
  containerC: {
    flex: 1,
    backgroundColor: Color.white,
    justifyContent: "space-between",
  },
  redceiptReceipt: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  vendorDetails: { gap: Gap.gap4, marginBottom: 12, paddingBottom: 10 },
  dashTop: {
    borderColor: Color.grey,
    height: 1,
    borderWidth: 1,
    marginBottom: 20,
    borderStyle: "dashed",
    width: "100%",
  },
  mb20: { marginBottom: 20 },
  mb10: { marginBottom: 10 },
  line1: {
    borderColor: Color.grey,
    height: 1,
    borderWidth: 1,
    marginBottom: 10,
    width: "100%",
  },
  dashBot: {
    borderColor: Color.grey,
    height: 1,
    borderWidth: 1,
    marginTop: 15,
    marginBottom: 15,
    borderStyle: "dashed",
    width: "100%",
  },
  voidButton: {
    borderWidth: 1,
    borderColor: Color.red,
    borderRadius: 4,
    alignItems: "center",
    width: 166,
  },
  addTransfer: {
    backgroundColor: Color.primary,
    borderRadius: 4,
    flexDirection: "row",
    gap: 10,
  },
  baSearch: {
    backgroundColor: Color.gray100,
    borderRadius: 4,
    height: 40,
    padding: 8,
    width: 240,
    marginVertical: 34,
  },
  baGapMargin: { gap: 24, marginBottom: 34 },
  baGapMargin2: { flexDirection: "row", gap: 24 },
  baGap8: { gap: 8 },
  baInputDim: { width: 240, height: 40 },
  baWidth: { width: 240 },
  baQtyInput: {
    backgroundColor: Color.gray100,
    borderRadius: 4,
    height: 40,
    padding: 8,
    width: 87,
  },
  baModalButton: {
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  action: {
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
    marginLeft: 20,
  },
  tab: {
    flexDirection: "row",
    gap: Gap.gap10,
    alignItems: "center",
  },
  voidTransaction1: {
    flex: 1,
    gap: 16,
    padding: 20,
  },
  voidTransaction2: {
    width: 319,
    backgroundColor: Color.secondary,
  },
  voidTransaction3: {
    backgroundColor: Color.white,
    flex: 1,
    padding: 10,
    gap: 8
},
  voidTransaction4: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    width: 320,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  voidTransaction5: {
    width: 24,
    height: 24,
    borderRadius: 100,
    backgroundColor: Color.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  voidTransaction6: {
    width: 319,
    paddingHorizontal: 20,
    paddingVertical: 8,
  },
  voidTransaction7: {
    paddingVertical: 16,
    paddingHorizontal: 32,
  },
  voidTransactionButton1: {
    margin: 24,
    alignItems: "center",
    backgroundColor: Color.primary,
    borderRadius: BorderRadius.b4,
  },
  confirmVoidContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 24,
  },
  passwordLabel2: { fontWeight: 400, fontSize: 14, lineHeight: 20 },
  confirmBAPasswordContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 24,
  },
  saleDetailsContainer1: {
    flexDirection: "row",
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: Color.white,
    height: 86,
    borderRadius: BorderRadius.b8,
  },
  themedHeaderTop1: {
    backgroundColor: Color.primary,
    padding: 12,
    flexDirection: "row",
    gap: 16,
    alignItems: "center",
  },
  themedHeaderTop2: {
    fontWeight: 400,
    fontSize: 20,
    lineHeight: 24,
    color: Color.white,
  },
  confirmBAPasswordContainer1: {
    flexDirection: "row",
    gap: 16,
  },
  ConfirmModal: {
    height: 170,
    width: 455,
    backgroundColor: Color.white,
    paddingHorizontal: 20,
    paddingVertical: 16,
    elevation: 10,
    gap: 16,
    borderRadius: 12,
  },
  ProductModalContent: {
    height: 480,
    width: 552,
    backgroundColor: Color.white,
    paddingHorizontal: 20,
    paddingVertical: 16,
    elevation: 10,
    gap: 10,
    borderRadius: 12,
  },
  tabLabelCollectionNew: {
    alignContent: "flex-start",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    paddingVertical: 20,
    paddingHorizontal: 16,
    gap: 8,
  },
  tableActionContainer: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 16,
  },
  tableActionPadder: {
    paddingLeft: 15,
  },
  addItemModal:{
    flex: 1,
    alignSelf: "flex-end",
    height: 500,
    backgroundColor: Color.white,
    paddingHorizontal: 20,
    paddingVertical: 16,
    elevation: 10,
    gap: 10,
  }
});
